### ISSUE TITLE
Tests broken with pip version > 22.0

### ISSUE THREAD

**Issue by onny** [zopefoundation/z3c.checkversions#22]
Hey,
tests seem broken with pip version > 22.0. I'm getting following error on NixOS trying to run them:

```
File "/nix/store/637dfk60yxy0f6pr1z24z506wycb50lv-python3.9-z3c-checkversions-1.2/lib/python3.9/site-packages/z3c/checkversions/buildout.txt", line 37, in buildout.txt
Failed example:
    checker.check()
Exception raised:
    Traceback (most recent call last):
      File "/nix/store/r8hi2lpzycparplcq0y663c43866f9bz-python3-3.9.13/lib/python3.9/doctest.py", line 1334, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest buildout.txt[13]>", line 1, in <module>
        checker.check()
      File "/nix/store/637dfk60yxy0f6pr1z24z506wycb50lv-python3.9-z3c-checkversions-1.2/lib/python3.9/site-packages/z3c/checkversions/base.py", line 89, in check
        self.pi.find_packages(req)
      File "/nix/store/7i745hc40p3vlszxc9j59qi42gry9m8j-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/package_index.py", line 477, in find_packages
        self.scan_url(self.index_url + requirement.unsafe_name + '/')
      File "/nix/store/7i745hc40p3vlszxc9j59qi42gry9m8j-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/package_index.py", line 817, in scan_url
        self.process_url(url, True)
      File "/nix/store/a32xqvx6s3798931qdyiivxy3d5fs1qn-python3.9-zc-buildout-3.0.0b2/lib/python3.9/site-packages/zc/buildout/patches.py", line 120, in process_url
        plinks = list(parse_links(html_page))
    TypeError: wrapper_wrapper() missing 1 required positional argument: 'use_deprecated_html5lib'
``` 

Also see https://hydra.nixos.org/build/183025377/nixlog/1

Best regards
Jonas

**Comment by icemac** [comment]
This is a problem in `zc.buildout` which was fixed in a newer release of that package.

**Comment by onny** [comment]
Thank you. Version 2.0 works now and I'm going to update it for NixOS
