### ISSUE TITLE
Script failures on versions deemed invalid by newer setuptools

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/z3c.checkversions#25]
### What I did:

On Zope `master`, which uses `z3c.checkversions`, I ran `bin/checkversions versions.cfg`

### What I expect to happen:

I expect the script to not blow up on versions deemed invalid by the underlying setuptools code, but report the issue and continue running.

### What actually happened:

In Zope's `versions-prod.cfg`, which is pulled in by `versions.cfg`, Zope itself is not pinned:

```
[versions]
Zope =
Zope2 = 4.0
...
```

This empty pin has never been an issue, but now I get this:

```
Traceback (most recent call last):
  File "/Users/jens/src/zope/Zope/bin/checkversions", line 12, in <module>
    sys.exit(z3c.checkversions.main.main())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jens/src/.eggs/z3c.checkversions-1.2-py3.11-macosx-13.0-arm64.egg/z3c/checkversions/main.py", line 91, in main
    checker.check(level=options.level)
  File "/Users/jens/src/.eggs/z3c.checkversions-1.2-py3.11-macosx-13.0-arm64.egg/z3c/checkversions/base.py", line 91, in check
    parsed_version = parse_version(version)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jens/src/zope/Zope/lib/python3.11/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: ''
```

Another pin that will blow up the script with a similar traceback is Zope's `tox.ini` that does a pin `zc.buildout >= 3.0.1`.

### What version of Python and Zope/Addons I am using:

Python 3.11.1, Zope `master`, pip 23.0.1, wheel 0.40.0, setuptools 67.6.0, zc.buildout 3.0.1, z3c.checkversions 1.2 (the problematic code is the same on 2.x).

Enclosing the call to `parsed_version = parse_version(version)` in the `check` method of the checker base class and catching exceptions will allow the script to report any such issues and continue working.

**Comment by dataflake** [comment]
This is a duplicate of #24
