### ISSUE TITLE
Breaks with setuptools >= 39

### ISSUE THREAD

**Issue by icemac** [zopefoundation/z3c.checkversions#8]
I have `setuptools` 39.0.1 installed and get the following error:

```python
$ bin/checkversions buildout.cfg
# Checking buildout file buildout.cfg
Traceback (most recent call last):
  File "bin/checkversions", line 12, in <module>
    sys.exit(z3c.checkversions.main.main())
  File ".../z3c.checkversions-0.5-py3.6.egg/z3c/checkversions/main.py", line 92, in main
    checker.check(level=options.level)
  File ".../z3c.checkversions-0.5-py3.6.egg/z3c/checkversions/base.py", line 103, in check
    if _final_version(parsed_version) and not _final_version(dist.parsed_version):
  File ".../z3c.checkversions-0.5-py3.6.egg/z3c/checkversions/base.py", line 23, in _final_version
    for part in parsed_version:
TypeError: 'Version' object is not iterable
```

Maybe related to #6.

**Comment by icemac** [comment]
The fix maybe could look like buildout/buildout#219 or what this code currently looks in `zc.buildout`.
